baseURL = "/"
languageCode = "cn"
title = "AUTUMN QUICHE"

defaultContentLanguage  = "cn"
theme = "kraiklyn"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

disablePathToLower = true

[params]
  externalTitle = ""
  sidebarColor = "quic"
  customCss = ["css/AutumnQuic.css"]

[markup]
  #defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.highlight]
      style = 'murphy'
      noClasses = false
