baseURL = "/"
languageCode = "cn"
title = "Autumn Navigation"

defaultContentLanguage  = "cn"
theme = "kraiklyn"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

disablePathToLower = true

[params]
  externalTitle = ""
  sidebarColor = "quic"
  customCss = ["css/fangqiuhang.css"]

[markup]
  #defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true